name: 06 - Contexts
run-name: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.run_number }}
on: 
    push:
        branches:
        - main
    workflow_dispatch:
       
jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name:  Display Information              
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number }}"
            - name: Retrieve Repository Information 
              run: |
                echo "Repository: ${{ github.repository }}"
                echo "Repository Owner: ${{ github.repository_owner }}"
                echo "Repository URL: ${{ github.server_url }}/${{ github.repository }}"
                echo "Repository Default Branch: ${{ github.event.repository.default_branch }}"
                echo "Repository Visibility: ${{ github.event.repository.visibility }}"
            - name: Retrieve Commit Information
              run: |
                echo "Commit Message: ${{ github.event.head_commit.message }}"
                echo "Commit Timestamp: ${{ github.event.head_commit.timestamp }}"
                echo "Commit Author Name: ${{ github.event.head_commit.author.name }}"
                echo "Commit Author Email: ${{ github.event.head_commit.author.email }}"
                echo "Commit Committer Name: ${{ github.event.head_commit.committer.name }}"
                echo "Commit Committer Email: ${{ github.event.head_commit.committer.email }}"
            - name: Retrieve Varibales 
              run: |
                echo "Variable Value: ${{ vars.MY_VAR }}"
                
              